"""add medications entity

Revision ID: 8deb968f95df
Revises: 1a2b3c4d5e6f
Create Date: 2025-11-14 22:11:08.020412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8deb968f95df'
down_revision: Union[str, None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('patients', sa.Column('preferred_medication_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'patients', 'medications', ['preferred_medication_id'], ['id'], ondelete='SET NULL')
    op.add_column('sessions', sa.Column('medication_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'sessions', 'medications', ['medication_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'medication_id')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'preferred_medication_id')
    op.drop_table('medications')
    # ### end Alembic commands ###
