"""add_body_compositions

Revision ID: c318a3da0db6
Revises: 8deb968f95df
Create Date: 2025-11-17 14:31:18.194560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c318a3da0db6'
down_revision: Union[str, None] = '8deb968f95df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_compositions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('fat_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fat_kg', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('muscle_mass_kg', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('h2o_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('metabolic_age', sa.Integer(), nullable=False),
    sa.Column('visceral_fat', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_body_compositions_patient_id'), 'body_compositions', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_body_compositions_patient_id'), table_name='body_compositions')
    op.drop_table('body_compositions')
    # ### end Alembic commands ###
