"""add_dosage_mg_and_activator_to_sessions

Revision ID: e4a209b88bcf
Revises: c318a3da0db6
Create Date: 2025-01-20 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4a209b88bcf'
down_revision: Union[str, None] = 'c318a3da0db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('activator_id', sa.UUID(), nullable=True))
    op.add_column('sessions', sa.Column('dosage_mg', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'activators', ['activator_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'dosage_mg')
    op.drop_column('sessions', 'activator_id')
    # ### end Alembic commands ###

