"""add cycle_date to cycles

Revision ID: f47e7f5820fa
Revises: e4a209b88bcf
Create Date: 2025-11-18 10:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f47e7f5820fa"
down_revision: Union[str, None] = "e4a209b88bcf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cycles",
        sa.Column(
            "cycle_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column("cycles", "cycle_date", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cycles", "cycle_date")
    # ### end Alembic commands ###


